markdown: redcarpet
permalink: /:categories/:title.html
url: 
lsi: false
pygments: true
safe: true
auto: false 

paginate: 8
paginate_path: "page:num"

# presonal config
domain: www.panxw.com
title: Panxw's Blog
description: Android, Cocos2d, Java Web, Linux, reading...
author: Steven Pan
email: winfirm#163.com
github: panxw

config:
  js_dir:
  img_dir:
  css_dir:
